# Generated by Django 3.1.5 on 2021-01-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appawward', '0002_auto_20210125_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='uploader',
            field=models.CharField(blank=True, default='default', max_length=40),
            preserve_default=False,
        ),
    ]
